### ISSUE TITLE
Is typing itself still broken?

### ISSUE THREAD

**Issue by EthraZa** [benjaminRomano/typings-installer#1]
I have used Get Typings And Save command, typed in "extjs" and saw it creating the typings folder with extjs/ExtJS.d.ts in it. It also created a tsd.json at project root with this:

{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "extjs/ExtJS.d.ts": {
      "commit": "fb2b3b1e068c9ff7d8f9b0851c08d37d96c95c38"
    }
  }
}

But when I type Ext. it is not opening up the autocomplete, even if I press ctrl+space it says "No suggestions".

Am I missing something?

**Comment by EthraZa** [comment]
Ops... TypeScript typing definitions and IntelliSense have no connectiong with each other, right? :/

**Comment by benjaminRomano** [comment]
Intellisense does work with TypeScript typing definitions.

I tested adding the extjs typings to my project, and it showed for me. However, I did have to create a tsconfig.json file to make intellisense work.
![image](https://cloud.githubusercontent.com/assets/9221137/11483783/06fce122-9770-11e5-8ba0-028d14b30756.png)

It's not always necessary to include a tsconfig.json to get intellisense. I think it might just depend on how the typings file is structured. For example, with the gulp typings, I can get intellisense in javascript code without the use of any tsconfig.json

Hope this helps. :smile:

**Comment by benjaminRomano** [comment]
I've created an issue at https://github.com/Microsoft/vscode/issues/835 to see if this expected behavior or not.

**Comment by EthraZa** [comment]
In the mean time would you be so kind to show what goes in the tsconfig.json?

Thank you.

**Comment by benjaminRomano** [comment]
Here's the tsconfig.json for this repo. Hope this helps. Otherwise you can find more info in the typescript github repo

``` js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "outDir": "out",
        "noLib": true,
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by benjaminRomano** [comment]
See https://github.com/Microsoft/vscode/issues/835 for more information about typings in vs code
