### ISSUE TITLE
Support for new versions of the Typings

### ISSUE THREAD

**Issue by mrmlnc** [benjaminRomano/typings-installer#2]
This extension does not support new versions of the Typings.

Example for the `typings@1.0.4`:
![2016-06-04_23-39-45](https://cloud.githubusercontent.com/assets/7034281/15801961/aea8ba06-2aad-11e6-8bed-ff1477b85ce3.gif)

Example for the `typings@0.8.1`:
![image](https://cloud.githubusercontent.com/assets/7034281/15801974/f9e960ec-2aad-11e6-9852-a778ae34e75b.png)

**Comment by benjaminRomano** [comment]
Thanks for letting me know. I'll look into this

**Comment by benjaminRomano** [comment]
Should be fixed now. Can you verify it works for you

**Comment by mrmlnc** [comment]
Thanks, it works :tada:
